repos:
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: "3.0.0"
    hooks:
      - id: shellcheck
        args:
          - .bash_aliases.sh
          - .bash_functions.sh
          - link.sh